# Generated by Django 5.1.6 on 2025-03-11 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bidding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it1', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='watchlists',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='watchlists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings2', to=settings.AUTH_USER_MODEL),
        ),
    ]
