# Generated by Django 5.1.6 on 2025-03-19 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bidding_item_alter_bidding_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlists',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='watchlists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='watchlists',
            unique_together={('user', 'item')},
        ),
    ]
