# Generated by Django 5.1.6 on 2025-03-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_watchlists_item_alter_watchlists_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.TextField(default='ongoing'),
        ),
    ]
